xarray_feature_scale:
  coords: {}
  attrs: {}
  dims: {}
  data_vars:
    QObs(mm/d):
      dims: []
      attrs: {}
      data: 1.945308804512024
    prcp(mm/day):
      dims: []
      attrs: {}
      data: 6.7543768882751465
    srad(W/m2):
      dims: []
      attrs: {}
      data: 130.48353576660156
    tmax(C):
      dims: []
      attrs: {}
      data: 10.010364532470703
    tmin(C):
      dims: []
      attrs: {}
      data: 9.679295539855957
    vp(Pa):
      dims: []
      attrs: {}
      data: 452.2418518066406
xarray_feature_center:
  coords: {}
  attrs: {}
  dims: {}
  data_vars:
    QObs(mm/d):
      dims: []
      attrs: {}
      data: 1.7935724258422852
    prcp(mm/day):
      dims: []
      attrs: {}
      data: 3.469590187072754
    srad(W/m2):
      dims: []
      attrs: {}
      data: 308.7041931152344
    tmax(C):
      dims: []
      attrs: {}
      data: 11.905956268310547
    tmin(C):
      dims: []
      attrs: {}
      data: 0.6090436577796936
    vp(Pa):
      dims: []
      attrs: {}
      data: 771.8810424804688
