batch_size: 64
cache_validation_data: true
clip_gradient_norm: 1
clip_targets_to_zero:
- QObs(mm/d)
commit_hash:
data_dir: data/CAMELS_US
dataset: camels_us
device: cpu
dynamic_inputs:
- prcp(mm/day)
- srad(W/m2)
- tmax(C)
- tmin(C)
- vp(Pa)
epochs: 3
experiment_name: camels_us_01022500_daymet
forcings:
- daymet
head: regression
hidden_size: 16
img_log_dir: runs/camels_us_01022500_daymet_1003_101549/img_log
initial_forget_bias: 3
learning_rate:
  0: 0.001
log_interval: 1
log_n_figures: 1
log_tensorboard: true
loss: MSE
metrics:
- NSE
- KGE
model: cudalstm
num_workers: 0
number_of_basins: 1
optimizer: Adam
output_activation: linear
output_dropout: 0.4
package_version: 1.13.0
predict_last_n: 1
run_dir: runs/camels_us_01022500_daymet_1003_101549
save_validation_results: false
save_weights_every: 1
seed: 111
seq_length: 30
target_variables:
- QObs(mm/d)
test_basin_file: basins/01022500.txt
test_end_date: 31/12/2002
test_start_date: 01/01/2002
train_basin_file: basins/01022500.txt
train_dir: runs/camels_us_01022500_daymet_1003_101549/train_data
train_end_date: 31/12/2000
train_start_date: 01/01/2000
validate_every: 1
validate_n_random_basins: 1
validation_basin_file: basins/01022500.txt
validation_end_date: 31/12/2001
validation_start_date: 01/01/2001
