# --- Experiment configurations --------------------------------------------------------------------
experiment_name: camels_us_01022500_daymet
run_dir: ./runs

train_basin_file: ./basins/01022500.txt
validation_basin_file: ./basins/01022500.txt
test_basin_file: ./basins/01022500.txt

train_start_date: "01/01/2000"
train_end_date: "31/12/2000"
validation_start_date: "01/01/2001"
validation_end_date: "31/12/2001"
test_start_date: "01/01/2002"
test_end_date: "31/12/2002"

seed: 111
device: cpu

# --- Validation configuration ---------------------------------------------------------------------
validate_every: 1
validate_n_random_basins: 1
cache_validation_data: True
metrics:
  - NSE
  - KGE

# --- Model configuration --------------------------------------------------------------------------
model: cudalstm
head: regression
output_activation: linear

hidden_size: 16
initial_forget_bias: 3
output_dropout: 0.4

# --- Training configuration -----------------------------------------------------------------------
optimizer: Adam
loss: MSE
learning_rate:
  0: 1e-3
batch_size: 64
epochs: 3
clip_gradient_norm: 1

predict_last_n: 1
seq_length: 30

num_workers: 0
log_interval: 1
log_tensorboard: True
log_n_figures: 1
save_weights_every: 1
save_validation_results: False

# --- Data configurations --------------------------------------------------------------------------
dataset: camels_us
data_dir: ./data/CAMELS_US
forcings:
  - daymet
dynamic_inputs:
  - prcp(mm/day)
  - srad(W/m2)
  - tmax(C)
  - tmin(C)
  - vp(Pa)
target_variables:
  - QObs(mm/d)
clip_targets_to_zero:
  - QObs(mm/d)
